apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mysql-pvc
  namespace: {{ .Values.namespace }}

spec:
  accessModes:
    - ReadWriteOnce

  annotations:
    helm.sh/resource-policy: keep
    
  storageClassName: {{ .Values.mysql.storage.class }}

  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}