# This file contains the definition of the Kubernetes Secret for the MySQL database.
apiVersion: v1
kind: Secret

# This file contains the definition of the Kubernetes Secret for the MySQL database.
metadata:
  name: mysql-secret
  namespace: clickncart

# type specifies the type of Kubernetes Secret being defined. In this case, it is an Opaque secret, which means it can store arbitrary key-value pairs.
type: Opaque

# stringData is a key-value map that contains the secret data in plain text. The values will be base64-encoded when the Secret is created.
stringData:
  MYSQL_ROOT_PASSWORD: rootroot