---
- name: check if AWS CLI is already installed 
  command: aws --version
  register: aws_cli_check
  failed_when: false
  changed-when: false

- name: download AWS CLI
  get_url: 
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip 
    mode: '0644'
  when: aws_cli_check.rc != 0

- name: extract AWS CLI 
  unarchive: 
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: true
  when: aws_cli_check.rc != 0

- name: install AWS CLI
  command: /tmp/aws/install
  when: aws_cli_check.rc != 0

- name: verify AWS CLI
  command: aws --version
  register: aws_cli_version
  changed_when: false

- name: display AWS CLI 
  debug:
    msg: "{{ aws_cli_version.stdout }}"