---
- name: create keyrings directory 
  file: 
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: add docker GPG key
  get_url: 
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: add docker repositories
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    # can use this too :"deb [arch={{ 'amd64' if ansible_facts['architecture'] == 'x86_64' else 'arm64' }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    state: present
    filename: docker

- name: update apt cache after adding docker repository
  apt:
    update_cache: true

- name: install docker
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: enable docker service
  systemd:
    name: docker
    enabled: true
    state: started
    
- name: add ubuntu user to docker group
  user: 
    name: ubuntu
    groups: docker
    append: true