---
- name: gets latest stable kubernetes version
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: true
  register: kubernetes_version
  changed_when: false

- name: download kubectl
  get_url:
    url: "https://dl.k8s.io/release/{{ kubernetes_version.content | trim }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: verify kubectl installation
  command: kubectl version --client
  register: kubectl_version
  changed_when: false

- name: display kubectl version
  debug:  
    msg: "{{ kubectl_version.stdout }}"