---

- name: install mysql client
  apt:
    name: 
      - mysql-client
    state: present

- name: verify mysql client installation
  command: mysql --version
  register: mysql_version
  changed_when: false

- name: display mysql client version
  debug:
    msg: "{{ mysql_version.stdout }}"
    