namespace: clickncart

mysql:
  replicaCount: 1

  image:
    repository: mysql
    tag: "8.4"

  rootPassword: DatabaseStrongPassword123!

  storage:
    size: 3Gi
    class: gp2

  service:
    port: 3306

  database:
    userdb: userdb
    catalogdb: catalogdb
    orderdb: orderdb

userService:
  replicaCount: 1

  image:
    repository: sumittiwari05/clickncart-user-service
    tag: v2
  
  service:
    port: 8081

  resources:
    requests:
      cpu: 250m
      memory: 512Mi

    limits:
      cpu: 500m
      memory: 1Gi

catalogService:
  replicaCount: 1

  image:
    repository: sumittiwari05/clickncart-catalog-service
    tag: v2

  service:
    port: 8082

  resources:
    requests:
      cpu: 250m
      memory: 512Mi

    limits:
      cpu: 500m
      memory: 1Gi

orderService:
  replicaCount: 1

  image:
    repository: sumittiwari05/clickncart-order-service
    tag: v2

  service:
    port: 8083

  resources:
    requests:
      cpu: 250m
      memory: 512Mi

    limits:
      cpu: 500m
      memory: 1Gi

frontend:
  replicaCount: 1

  image:
    repository: sumittiwari05/clickncart-frontend
    tag: v1

  service:
    port: 80

  resources:
    requests:
      cpu: 128m
      memory: 256Mi

    limits:
      cpu: 300m
      memory: 512Mi

ingress:
  enabled: true