apiVersion: v1
kind: Service

metadata:
  name: frontend
  namespace: clickncart

spec:
  selector:
    app: frontend

  ports:
    - port: 80
      targetPort: 80
      # we are not using ingress so for now we are going with nodePort. use it when not using ingress.
      # nodePort: 30080

  type: ClusterIP # use NodePort only when using nodePort