# Persistent Volume Claim for MySQL
apiVersion: v1

# kind specifies the type of Kubernetes resource being defined, which is PersistentVolumeClaim here.
kind: PersistentVolumeClaim

# metadata contains metadata about the PersistentVolumeClaim, including its name and namespace.
metadata:
  name: mysql-pvc
  namespace: clickncart

# spec defines the desired characteristics of the PersistentVolumeClaim, including access modes and resource requests.
spec:
  accessModes:
    # specifying that the volume can be mounted as read-write by a single node.
    - ReadWriteOnce

  storageClassName: gp2

  # defining the resource requests for the PersistentVolumeClaim, specifically the amount of storage requested.
  resources:
    requests:
      # requesting 5Gi of storage for the PersistentVolumeClaim.
      storage: 3Gi