apiVersion: v1
kind: Service

metadata:
  name: mysql
  namespace: clickncart

# spec defines the desired state of the Service, including the selector and ports.
spec:
  selector:
    app: mysql

  # ports defines the list of ports that the Service exposes. Here, it exposes port 3306 for MySQL.
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
    
  # type specifies the type of Service being defined. In this case, it is a ClusterIP service, which means it is only accessible within the Kubernetes cluster.
  type: ClusterIP