---
- name: Download AWS CLI v2 installer
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: /tmp/awscliv2.zip

- name: Unzip installer
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: yes

- name: Run AWS CLI installer
  command: /tmp/aws/install
  args:
    creates: /usr/local/bin/aws