{{ include "user-service.versionedHPA" (dict "root" $ "version" .Values.liveVersion) }}

{{- if .Values.candidateVersion }}
---
{{ include "user-service.versionedHPA" (dict "root" $ "version" .Values.candidateVersion) }}
{{- end }}

{{- range .Values.retiredVersions }}
---
{{ include "user-service.versionedHPA" (dict "root" $ "version" .version) }}
{{- end }}
