{{ include "user-service.versionedPDB" (dict "version" .Values.liveVersion) }}

{{- if .Values.candidateVersion }}
---
{{ include "user-service.versionedPDB" (dict "version" .Values.candidateVersion) }}
{{- end }}

{{- range .Values.retiredVersions }}
---
{{ include "user-service.versionedPDB" (dict "version" .version) }}
{{- end }}
