{{ include "frontend.versionedDeployment" (dict "root" $ "version" .Values.liveVersion "imageTag" (index .Values.imageTags (printf "v%v" .Values.liveVersion)) "retiredAt" "") }}

{{- if .Values.candidateVersion }}
---
{{ include "frontend.versionedDeployment" (dict "root" $ "version" .Values.candidateVersion "imageTag" (index .Values.imageTags (printf "v%v" .Values.candidateVersion)) "retiredAt" "") }}
{{- end }}

{{- range .Values.retiredVersions }}
---
{{ include "frontend.versionedDeployment" (dict "root" $ "version" .version "imageTag" (index $.Values.imageTags (printf "v%v" .version)) "retiredAt" .retiredAt) }}
{{- end }}
