apiVersion: apps/v1
kind: Deployment

metadata:
  name: catalog-service
  namespace: clickncart

spec:
  replicas: 1

  selector:
    matchLabels:
      app: catalog-service

  template:
    metadata:
      labels:
        app: catalog-service

    spec:
      containers:
        - name: catalog-service
          image: sumittiwari05/clickncart-catalog-service:v1

          imagePullPolicy: Always

          ports:
            - containerPort: 8082

          env:
            - name: MYSQL_HOST
              value: mysql

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD