[jumpserver]
jumpserver ansible_host=<jumpsever_private_ip> 
# can get it by "terraform output jumpserver_private_ip"

[jumpserver:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519
