# This file contains the definition of the Kubernetes namespace for the ClickNcart application.

# apiVersion specifies the version of the Kubernetes API to use for this resource definition.
apiVersion: v1

# kind specifies the type of Kubernetes resource being defined, which is Namespace here.
kind: Namespace

# metadata contains metadata about the namespace, including its name.
metadata:
  name: clickncart
