image:
  repository: REPLACE_WITH_ECR_URL/clickncart/frontend

liveVersion: 1
candidateVersion: ~
imageTags:
  v1: "1.0.1"
retiredVersions: []

replicaCount: 2

resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits:   { cpu: 200m, memory: 256Mi }

nodeSelector:
  role: frontend
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "frontend"
    effect: "NoSchedule"

hpa:
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
